# Generated by Django 4.1.4 on 2022-12-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_treino'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='nome',
            field=models.CharField(default='Atleta', max_length=100),
        ),
    ]
