# Generated by Django 4.1.4 on 2022-12-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atleta_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='linkStrava',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
