# Generated by Django 4.1.4 on 2022-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_treino_linkstrava'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='modalidade',
            field=models.CharField(default='Treino', max_length=100),
        ),
    ]
